{
 "title": "Energieverbruik",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "L1",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reading_INSTANTANEOUS_ACTIVE_POWER_L1_CONSUMED",
     "legendFormat": "/"
    }
   ]
  },
  {
   "title": "L2",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reading_INSTANTANEOUS_ACTIVE_POWER_L2_CONSUMED",
     "legendFormat": "/"
    }
   ]
  },
  {
   "title": "L3",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reading_INSTANTANEOUS_ACTIVE_POWER_L3_CONSUMED",
     "legendFormat": "/"
    }
   ]
  },
  {
   "title": "Waterverbruik",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "flowlpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(reading_watermeter_reading_current_value[1m])",
     "legendFormat": "/"
    }
   ]
  },
  {
   "title": "-L1",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reading_INSTANTANEOUS_ACTIVE_POWER_L1_DELIVERED",
     "legendFormat": "/"
    }
   ]
  },
  {
   "title": "-L2",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reading_INSTANTANEOUS_ACTIVE_POWER_L2_DELIVERED",
     "legendFormat": "/"
    }
   ]
  },
  {
   "title": "-L3",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reading_INSTANTANEOUS_ACTIVE_POWER_L3_DELIVERED",
     "legendFormat": "/"
    }
   ]
  },
  {
   "title": "Gasverbruik",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "delta(reading_GAS_READING[1h])", "legendFormat": "/" }
   ]
  },
  {
   "title": "Stroom",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "expr": "reading_INSTANTANEOUS_ACTIVE_POWER_L1_CONSUMED",
     "legendFormat": "L1"
    },
    {
     "expr": "reading_INSTANTANEOUS_ACTIVE_POWER_L2_CONSUMED",
     "legendFormat": "L2"
    },
    {
     "expr": "reading_INSTANTANEOUS_ACTIVE_POWER_L3_CONSUMED",
     "legendFormat": "L3"
    },
    {
     "expr": "-reading_INSTANTANEOUS_ACTIVE_POWER_L1_DELIVERED",
     "legendFormat": "-L1"
    },
    {
     "expr": "-reading_INSTANTANEOUS_ACTIVE_POWER_L2_DELIVERED",
     "legendFormat": "-L2"
    },
    {
     "expr": "-reading_INSTANTANEOUS_ACTIVE_POWER_L3_DELIVERED",
     "legendFormat": "-L3"
    }
   ]
  },
  {
   "title": "Gasverbruik",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 10 },
   "targets": [
    { "expr": "reading_GAS_READING", "legendFormat": "Gas" }
   ]
  },
  {
   "title": "Water",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 17 },
   "targets": [
    {
     "expr": "reading_watermeter_reading_current_value"
    }
   ]
  }
 ]
}